[[Libksba]]
arch = "aarch64"
git-tree-sha1 = "962292e1f42524e294cb646d9045ea0c698122ee"
os = "macos"

    [[Libksba.download]]
    sha256 = "9b82f850082f2514bb1a4658375d1ecd7be6bea1fe88056ba8b26be425e71b01"
    url = "https://github.com/JuliaBinaryWrappers/Libksba_jll.jl/releases/download/Libksba-v1.6.8+0/Libksba.v1.6.8.aarch64-apple-darwin.tar.gz"
[[Libksba]]
arch = "aarch64"
git-tree-sha1 = "025183b9abaf50a407d26a2c4dc13578a70f683a"
libc = "glibc"
os = "linux"

    [[Libksba.download]]
    sha256 = "a54979f7c07374a99076679ad1966eb744d5e6922f1da9d9c03ab50ea35ea34a"
    url = "https://github.com/JuliaBinaryWrappers/Libksba_jll.jl/releases/download/Libksba-v1.6.8+0/Libksba.v1.6.8.aarch64-linux-gnu.tar.gz"
[[Libksba]]
arch = "aarch64"
git-tree-sha1 = "1c7e404d55f1b595184a0d8f22bdc93d9576e7eb"
libc = "musl"
os = "linux"

    [[Libksba.download]]
    sha256 = "cf6d60a57610a11e042eca4bfdc02e2d1d1c9f88db752ab7844ceed733a91295"
    url = "https://github.com/JuliaBinaryWrappers/Libksba_jll.jl/releases/download/Libksba-v1.6.8+0/Libksba.v1.6.8.aarch64-linux-musl.tar.gz"
[[Libksba]]
arch = "aarch64"
git-tree-sha1 = "62fdd4baac5f94a3d62ecd150d0ae63f598bdb05"
os = "freebsd"

    [[Libksba.download]]
    sha256 = "c3f96f6e4e88c162d5972870ee3c7f817914e35829328cb5ac6ab12b00ba832d"
    url = "https://github.com/JuliaBinaryWrappers/Libksba_jll.jl/releases/download/Libksba-v1.6.8+0/Libksba.v1.6.8.aarch64-unknown-freebsd.tar.gz"
[[Libksba]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1699649388e8ccdbd9cd342aa4f9573e7629a6ca"
libc = "glibc"
os = "linux"

    [[Libksba.download]]
    sha256 = "94d77c35505b3503e1c2e8d14756993674a5d5ce279f3b3e7a63caa2e43fd4a0"
    url = "https://github.com/JuliaBinaryWrappers/Libksba_jll.jl/releases/download/Libksba-v1.6.8+0/Libksba.v1.6.8.armv6l-linux-gnueabihf.tar.gz"
[[Libksba]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "aad7bf905dc39f170851b9d44c8999a80e02e5a7"
libc = "musl"
os = "linux"

    [[Libksba.download]]
    sha256 = "012ac7f8141667259f9ac2059b4fea36feca9c74b5215fe0d25416676f679cac"
    url = "https://github.com/JuliaBinaryWrappers/Libksba_jll.jl/releases/download/Libksba-v1.6.8+0/Libksba.v1.6.8.armv6l-linux-musleabihf.tar.gz"
[[Libksba]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d17525f4e10c114c6a83eda4eaf6020eefac65f0"
libc = "glibc"
os = "linux"

    [[Libksba.download]]
    sha256 = "60419837bca34dd56b58c9d996b0fbe00ab420c823874395b7457c0c9d8770bb"
    url = "https://github.com/JuliaBinaryWrappers/Libksba_jll.jl/releases/download/Libksba-v1.6.8+0/Libksba.v1.6.8.armv7l-linux-gnueabihf.tar.gz"
[[Libksba]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c8a338b1f11cf4c9f26faa2400f12648b173d76c"
libc = "musl"
os = "linux"

    [[Libksba.download]]
    sha256 = "e4247ec496cd037c9b1427914946c4a7679af9c7ac659173115c0a075268fb92"
    url = "https://github.com/JuliaBinaryWrappers/Libksba_jll.jl/releases/download/Libksba-v1.6.8+0/Libksba.v1.6.8.armv7l-linux-musleabihf.tar.gz"
[[Libksba]]
arch = "i686"
git-tree-sha1 = "eba8172c3ff3f1743d48c56798555116b84dc675"
libc = "glibc"
os = "linux"

    [[Libksba.download]]
    sha256 = "73ae28cc002defa2f8e79303090a626b1712a8917d058ca41303bdf839dce2da"
    url = "https://github.com/JuliaBinaryWrappers/Libksba_jll.jl/releases/download/Libksba-v1.6.8+0/Libksba.v1.6.8.i686-linux-gnu.tar.gz"
[[Libksba]]
arch = "i686"
git-tree-sha1 = "765f7c3b694861fd3311220fd2c7edaa3b53ad26"
libc = "musl"
os = "linux"

    [[Libksba.download]]
    sha256 = "123ea038020a26757e3f29b7e47b15397b536d26c82b802a7af9a1ada2fdc10c"
    url = "https://github.com/JuliaBinaryWrappers/Libksba_jll.jl/releases/download/Libksba-v1.6.8+0/Libksba.v1.6.8.i686-linux-musl.tar.gz"
[[Libksba]]
arch = "i686"
git-tree-sha1 = "184ffe290860eb81b321d6cbcfc71ebed333aba4"
os = "windows"

    [[Libksba.download]]
    sha256 = "f8a59b68271517763a8caee1734bd080b6f80b89e83f02f88e291cf02757f5c7"
    url = "https://github.com/JuliaBinaryWrappers/Libksba_jll.jl/releases/download/Libksba-v1.6.8+0/Libksba.v1.6.8.i686-w64-mingw32.tar.gz"
[[Libksba]]
arch = "powerpc64le"
git-tree-sha1 = "c3172fdd11da5dad97093e7a44587f2e4e0c3030"
libc = "glibc"
os = "linux"

    [[Libksba.download]]
    sha256 = "1cd7300ab23dfac30301dfec871244c36b893e660a3f6228a7861e7b97d1fb4e"
    url = "https://github.com/JuliaBinaryWrappers/Libksba_jll.jl/releases/download/Libksba-v1.6.8+0/Libksba.v1.6.8.powerpc64le-linux-gnu.tar.gz"
[[Libksba]]
arch = "riscv64"
git-tree-sha1 = "290de253eb79aaafbc10670730a0543a4208bc36"
libc = "glibc"
os = "linux"

    [[Libksba.download]]
    sha256 = "63a314f1b70453ff3b77e0ed4a21f471be2d16104729a06c7a5e925e505bb6a9"
    url = "https://github.com/JuliaBinaryWrappers/Libksba_jll.jl/releases/download/Libksba-v1.6.8+0/Libksba.v1.6.8.riscv64-linux-gnu.tar.gz"
[[Libksba]]
arch = "x86_64"
git-tree-sha1 = "64627afe176b6b43dbe8210cfdf4914f1f39a41b"
os = "macos"

    [[Libksba.download]]
    sha256 = "05072daeb5ca5657205051cc377f77a30b6556f0074eeb6ef5bfd3941bb11540"
    url = "https://github.com/JuliaBinaryWrappers/Libksba_jll.jl/releases/download/Libksba-v1.6.8+0/Libksba.v1.6.8.x86_64-apple-darwin.tar.gz"
[[Libksba]]
arch = "x86_64"
git-tree-sha1 = "64c0b67a7404339d22cbc2326d02d750a647cb52"
libc = "glibc"
os = "linux"

    [[Libksba.download]]
    sha256 = "8f4debb44bd45b61b7115db624b4d784013cf05ecb0f7e1564ca819af3002940"
    url = "https://github.com/JuliaBinaryWrappers/Libksba_jll.jl/releases/download/Libksba-v1.6.8+0/Libksba.v1.6.8.x86_64-linux-gnu.tar.gz"
[[Libksba]]
arch = "x86_64"
git-tree-sha1 = "06c69e2fe2b89dee127d07baa85304e0748644bd"
libc = "musl"
os = "linux"

    [[Libksba.download]]
    sha256 = "76d99892927e0cf931ec7dc378ad548be0ed48b4b45048ef8d60504aa64324ef"
    url = "https://github.com/JuliaBinaryWrappers/Libksba_jll.jl/releases/download/Libksba-v1.6.8+0/Libksba.v1.6.8.x86_64-linux-musl.tar.gz"
[[Libksba]]
arch = "x86_64"
git-tree-sha1 = "21972f9e8b0269c1c8ebaf5c273c519cd0b41578"
os = "freebsd"

    [[Libksba.download]]
    sha256 = "7045784dee36962ed9efec2ba5d35d90461996719587ffd0c1caf857deb47b82"
    url = "https://github.com/JuliaBinaryWrappers/Libksba_jll.jl/releases/download/Libksba-v1.6.8+0/Libksba.v1.6.8.x86_64-unknown-freebsd.tar.gz"
[[Libksba]]
arch = "x86_64"
git-tree-sha1 = "ff92923388668b474ed3dd75eff6c35d06eac90d"
os = "windows"

    [[Libksba.download]]
    sha256 = "09b3617a36e2c937286c88478ebe48deda09fc6c03a96d6b7362c98800de5eb2"
    url = "https://github.com/JuliaBinaryWrappers/Libksba_jll.jl/releases/download/Libksba-v1.6.8+0/Libksba.v1.6.8.x86_64-w64-mingw32.tar.gz"
